# Generated by Django 4.2.2 on 2023-06-14 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('lolchamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.lolchamp')),
            ],
        ),
    ]
