# Generated by Django 4.2.2 on 2023-06-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_abilities_ability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ability name'),
        ),
    ]
